// This file is auto-generated by plugins/with-component-registry.ts
// Do not edit this file manually

import { Avatar, AvatarImage, AvatarFallback } from './ui/avatar'
import { Badge } from './ui/badge'
import { ButtonGroup } from './ui/button-group'
import { Button } from './ui/button'
import { Card, CardContent, CardImage, CardFooter } from './ui/card'
import { Checkbox } from './ui/checkbox'
import { Chip } from './ui/chip'
import { ContextMenu, ContextMenuTrigger, ContextMenuContent, ContextMenuItem, ContextMenuCheckboxItem, ContextMenuRadioItem, ContextMenuLabel, ContextMenuSeparator, ContextMenuShortcut, ContextMenuGroup, ContextMenuPortal, ContextMenuSub, ContextMenuSubContent, ContextMenuSubTrigger, ContextMenuRadioGroup } from './ui/context-menu'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogOverlay, DialogPortal, DialogTitle, DialogTrigger, DialogClose } from './ui/dialog'
import { Divider } from './ui/divider'
import { DropdownMenu, DropdownMenuPortal, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuGroup, DropdownMenuLabel, DropdownMenuItem, DropdownMenuCheckboxItem, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuSub, DropdownMenuSubTrigger, DropdownMenuSubContent } from './ui/dropdown-menu'
import { Loading } from './ui/loading'
import { NavigationBar, NavigationBarItem } from './ui/navigation-bar'
import { NavigationRail, NavigationRailContent, NavigationRailMenu, NavigationRailTrigger, NavigationRailItem } from './ui/navigation-rail'
import { Progress } from './ui/progress'
import { RadioGroup, RadioGroupItem } from './ui/radio-group'
import { Ripple } from './ui/ripple'
import { Slider } from './ui/slider'
import { toast, Snakebar } from './ui/snakebar'
import { Switch } from './ui/switch'
import { Tabs, TabsList, TabsTrigger, TabsContent } from './ui/tabs'
import { TextField } from './ui/text-field'
import { Toggle } from './ui/toggle'
import { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from './ui/tooltip'

const registry = {
  Avatar,
  AvatarImage,
  AvatarFallback,
  Badge,
  ButtonGroup,
  Button,
  Card,
  CardContent,
  CardImage,
  CardFooter,
  Checkbox,
  Chip,
  ContextMenu,
  ContextMenuTrigger,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuCheckboxItem,
  ContextMenuRadioItem,
  ContextMenuLabel,
  ContextMenuSeparator,
  ContextMenuShortcut,
  ContextMenuGroup,
  ContextMenuPortal,
  ContextMenuSub,
  ContextMenuSubContent,
  ContextMenuSubTrigger,
  ContextMenuRadioGroup,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogPortal,
  DialogTitle,
  DialogTrigger,
  DialogClose,
  Divider,
  DropdownMenu,
  DropdownMenuPortal,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuLabel,
  DropdownMenuItem,
  DropdownMenuCheckboxItem,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubTrigger,
  DropdownMenuSubContent,
  Loading,
  NavigationBar,
  NavigationBarItem,
  NavigationRail,
  NavigationRailContent,
  NavigationRailMenu,
  NavigationRailTrigger,
  NavigationRailItem,
  Progress,
  RadioGroup,
  RadioGroupItem,
  Ripple,
  Slider,
  toast,
  Snakebar,
  Switch,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  TextField,
  Toggle,
  Tooltip,
  TooltipTrigger,
  TooltipContent,
  TooltipProvider
}

export default registry
